from typing import Any
from machine import Pin

def dht_readinto(*args, **kwargs) -> Any: ...

class DHT22:
    def humidity(self, *args, **kwargs) -> Any: ...
    def temperature(self, *args, **kwargs) -> Any: ...
    def measure(self, *args, **kwargs) -> Any: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class DHT11:
    def humidity(self) -> int: ...
    def temperature(self) -> int: ...
    def measure(self): ...
    def __init__(self, pin: Pin) -> None: ...

class DHTBase:
    def measure(self, *args, **kwargs) -> Any: ...
    def __init__(self, *argv, **kwargs) -> None: ...
