from ctypes import Union
from typing import Any, Optional

WDT_RESET: int
PWRON_RESET: int

def disable_irq(*args, **kwargs) -> Any: ...
def soft_reset(*args, **kwargs) -> Any: ...
def enable_irq(*args, **kwargs) -> Any: ...
def bitstream(*args, **kwargs) -> Any: ...
def deepsleep(*args, **kwargs) -> Any: ...
def bootloader(*args, **kwargs) -> Any: ...
def reset(*args, **kwargs) -> Any: ...
def freq(*args, **kwargs) -> Any: ...
def reset_cause(*args, **kwargs) -> Any: ...
def idle(*args, **kwargs) -> Any: ...
def time_pulse_us(*args, **kwargs) -> Any: ...
def lightsleep(*args, **kwargs) -> Any: ...
def unique_id(*args, **kwargs) -> Any: ...

class WDT:
    def feed(self, *args, **kwargs) -> Any: ...
    def __init__(self, *argv, **kwargs) -> None: ...

mem8: Any
mem32: Any
mem16: Any

class PWM:
    def freq(self, *args, **kwargs) -> Any: ...
    def duty_u16(self, *args, **kwargs) -> Any: ...
    def duty_ns(self, *args, **kwargs) -> Any: ...
    def deinit(self, *args, **kwargs) -> Any: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class ADC:
    CORE_TEMP: int
    def read_u16(self, *args, **kwargs) -> Any: ...
    def __init__(
        self,
        channel=0,
        *,
        sample: int,
    ) -> None: ...

class I2C:
    def readfrom_mem_into(
        self, addr: int, memaddr: int, buf: bytes, *, addrsize: int = 8
    ) -> None: ...
    def readfrom_into(self, addr: int, buf: bytes, stop: bool = True, /) -> None: ...
    def readfrom_mem(
        self, memaddr: int, nbytes: int, *, addrsize: int = 8
    ) -> bytes: ...
    def writeto_mem(
        self, addr: int, memaddr: int, buf: bytes, *, addrsize: int = 8
    ) -> None: ...
    def scan(self) -> list[int]: ...
    def writeto(self, addr: int, buf: bytes, stop: bool = True, /) -> int: ...
    def writevto(self, addr: int, vector: bytes, stop: bool = True, /) -> int: ...
    def start(self): ...
    def readfrom(self, addr: int, nbytes: int, stop: bool = True, /) -> bytes: ...
    def readinto(self, buf: bytes, nack: bool = True): ...
    def init(self, scl: Pin, sda: Pin, *, freq=400_000): ...
    def stop(self): ...
    def write(self, buf: bytes): ...
    def __init__(
        self, id: int = 0, *, scl: Pin = Pin(9), sda: Pin = Pin(8), freq=400_000
    ): ...

class I2S:
    RX: int
    MONO: int
    STEREO: int
    TX: int
    def shift(self, *args, **kwargs) -> Any: ...
    def init(self, *args, **kwargs) -> Any: ...
    def irq(self, *args, **kwargs) -> Any: ...
    def readinto(self, *args, **kwargs) -> Any: ...
    def deinit(self, *args, **kwargs) -> Any: ...
    def write(self, *args, **kwargs) -> Any: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class Pin:
    PULL_DOWN: int
    IRQ_RISING: int
    OPEN_DRAIN: int
    OUT: int
    IRQ_FALLING: int
    PULL_UP: int
    ALT: int
    IN: int
    def toggle(self, *args, **kwargs) -> Any: ...
    def low(self, *args, **kwargs) -> Any: ...
    def off(self, *args, **kwargs) -> Any: ...
    def on(self, *args, **kwargs) -> Any: ...
    def irq(self, *args, **kwargs) -> Any: ...
    def value(self, *args, **kwargs) -> Any: ...
    def high(self, *args, **kwargs) -> Any: ...
    def init(self, *args, **kwargs) -> Any: ...
    def __init__(
        self,
        id: int,
        mode: int = -1,
        pull: int = -1,
        *,
        value: Optional[int] = None,
        drive: int = 0,
        alt: int = -1,
    ) -> None: ...

class SoftSPI:
    LSB: int
    MSB: int
    def deinit(self, *args, **kwargs) -> Any: ...
    def init(self, *args, **kwargs) -> Any: ...
    def write_readinto(self, *args, **kwargs) -> Any: ...
    def read(self, *args, **kwargs) -> Any: ...
    def write(self, *args, **kwargs) -> Any: ...
    def readinto(self, *args, **kwargs) -> Any: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class Timer:
    PERIODIC: int
    ONE_SHOT: int
    def init(self, *args, **kwargs) -> Any: ...
    def deinit(self, *args, **kwargs) -> Any: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class UART:
    INV_TX: int
    CTS: int
    INV_RX: int
    RTS: int
    def deinit(self): ...
    def init(
        self,
        baudrate: int = 9600,
        bits: int = 8,
        parity: Optional[int] = None,
        stop: int = 1,
    ): ...
    def sendbreak(self): ...
    def read(self, nbytes: int = 0) -> Optional[bytes]: ...
    def any(self) -> int: ...
    def write(self, buf: bytes) -> int: ...
    def readinto(self, buf, nbytes: int = 0) -> Any: ...
    def readline(self) -> Optional[bytes]: ...
    def __init__(
        self,
        id: int = 0,
        *,
        tx: Pin = Pin(0),
        rx: Pin = Pin(1),
        rts: Optional[Pin] = None,
        cts: Optional[Pin] = None,
        txbuf: int = 256,
        rxbuf: int = 256,
        timeout: int = 0,
        timeout_char: int = 1,
        invert: Optional[int] = None,
        flow: Optional[int] = None,
    ): ...

class SoftI2C:
    def readfrom_mem_into(self, *args, **kwargs) -> Any: ...
    def readfrom_into(self, *args, **kwargs) -> Any: ...
    def readfrom_mem(self, *args, **kwargs) -> Any: ...
    def writeto_mem(self, *args, **kwargs) -> Any: ...
    def scan(self, *args, **kwargs) -> Any: ...
    def writeto(self, *args, **kwargs) -> Any: ...
    def writevto(self, *args, **kwargs) -> Any: ...
    def start(self, *args, **kwargs) -> Any: ...
    def readfrom(self, *args, **kwargs) -> Any: ...
    def readinto(self, *args, **kwargs) -> Any: ...
    def init(self, *args, **kwargs) -> Any: ...
    def stop(self, *args, **kwargs) -> Any: ...
    def write(self, *args, **kwargs) -> Any: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class RTC:
    def datetime(self, *args, **kwargs) -> Any: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class SPI:
    LSB: int
    MSB: int
    def deinit(self, *args, **kwargs) -> Any: ...
    def init(self, *args, **kwargs) -> Any: ...
    def write_readinto(self, *args, **kwargs) -> Any: ...
    def read(self, *args, **kwargs) -> Any: ...
    def write(self, *args, **kwargs) -> Any: ...
    def readinto(self, *args, **kwargs) -> Any: ...
    def __init__(self, *argv, **kwargs) -> None: ...

class Signal:
    def off(self, *args, **kwargs) -> Any: ...
    def on(self, *args, **kwargs) -> Any: ...
    def value(self, *args, **kwargs) -> Any: ...
    def __init__(self, *argv, **kwargs) -> None: ...
