from typing import Any, Tuple

def ticks_diff(ticks1: int, ticks2: int) -> int: ...
def ticks_add(ticks: int, delta: int) -> int: ...
def ticks_cpu() -> int: ...
def time() -> int: ...
def ticks_ms() -> int: ...
def ticks_us() -> int: ...
def time_ns() -> int: ...
def localtime() -> Tuple[int, int, int, int, int, int, int, int]: ...
def sleep_us(us: int): ...
def gmtime() -> Tuple[int, int, int, int, int, int, int, int]: ...
def sleep_ms(ms: int): ...
def mktime(*args, **kwargs) -> Any: ...
def sleep(seconds: int): ...
